<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Syntax highlighting support for the Laravel Blade markup.</string>
	<key>fileTypes</key>
	<array>
		<string>blade.php</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\@\b(section)\b(?=(|\s*|)\()</string>
	<key>foldingStopMarker</key>
	<string>\)(?!.*\))</string>
	<key>injections</key>
	<dict>
		<key>text.html.php.laravel-blade - (meta.embedded | meta.tag), L:text.html.php.laravel-blade meta.tag, L:source.js.embedded.html</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s*)(?=&lt;\?(?![^?]*\?&gt;))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.leading.php</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)(\s*$\n)?</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.embedded.trailing.php</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>&lt;\?(?i:php|=)?</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.begin.php</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>source.php</string>
							<key>end</key>
							<string>(\?)&gt;</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.end.php</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>source.php</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.embedded.block.php</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.html.php#language</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;\?(?i:php|=)?(?![^?]*\?&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.php</string>
					<key>end</key>
					<string>(\?)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.php</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.php</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php#language</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;\?(?i:php|=)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.php</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.php</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.line.php</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>source.php</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.end.php</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>source.php</string>
								</dict>
							</dict>
							<key>match</key>
							<string>\G(\s*)((\?))(?=&gt;)</string>
							<key>name</key>
							<string>meta.special.empty-tag.php</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\G</string>
							<key>contentName</key>
							<string>source.php</string>
							<key>end</key>
							<string>(\?)(?=&gt;)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.section.embedded.end.php</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>source.php</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.html.php#language</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{\{--</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.laravel-blade.php</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Laravel Blade Comments</string>
					<key>end</key>
					<string>--\}\}</string>
					<key>name</key>
					<string>comment.block.laravel-blade.php</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{(!!)|(\{\{\{?)-?</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Catches the remainder.</string>
					<key>end</key>
					<string>-?(\}?\}\})|(!!)\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.php.embedded.line.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php#language</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>@\{\{\{?-?</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Catches the remainder.</string>
					<key>end</key>
					<string>-?\}?\}\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
					</dict>
					<key>name</key>
					<string>embedded.line.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s{0}|^)(\@)\b(if|elseif|forelse|foreach|for|while|extends|unless|each|yield|lang|choice|section|include)\b(?=(|\s*|)\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.laravel-blade</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Laravel Blade Stock Compiler Calls</string>
					<key>end</key>
					<string>\)(?!.*\))</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>compiler.bounds.laravel-blade</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.php.embedded.line.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php#language</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s{0}|^)(\@)\b(.+)\b(?=(|\s*|)\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.laravel-blade</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.laravel-blade</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Laravel Blade Custom Compiler Calls</string>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>compiler.bounds.laravel-blade</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.php.embedded.line.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php#language</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s{0}|^)(\@)\b(endif|endforelse|endforeach|endfor|endwhile|else|endunless|show|stop|endsection|parent|overwrite)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.laravel-blade</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.laravel-blade</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Laravel Blade Stock Compiler Closure</string>
					<key>end</key>
					<string></string>
					<key>name</key>
					<string>source.php.embedded.line.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php#language</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s{0}|^)(\@)\b([a-zA-Z_]+)\b(\s?)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.laravel-blade</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.laravel-blade</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Laravel Blade Custom Compiler Closure</string>
					<key>end</key>
					<string></string>
					<key>name</key>
					<string>source.php.embedded.line.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.php#language</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>PHP - Laravel Blade</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.php.laravel-blade</string>
	<key>uuid</key>
	<string>70911d1c-0a7c-4cb5-9771-d71d23d8ab1a</string>
</dict>
</plist>
